// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image2":
            case "pigon":return img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
........ccccc...................
......ccbbbbbc..................
....ccddbbbbbbf.................
...cbbbddbbffbf.................
....ffffdbbffbff................
.......fbbbbbbbf................
.......fbbbbbbbff...............
......ffbbbbbbbbfff.............
......f6bbbbbb663ddcc...........
.....cc66bbbb666dddddc..........
.....cd36666663dddddddc.........
.....cddd3333dbddddddbcc........
.....cddddddddbdddddbbddc.......
.....cddddddddbbdddbbdddbc......
......cddddddddbbdbbddddbbccc...
......ccddddddddbbbbcccccbbbcc..
.......ccddddddddddddddbccffff..
........cccbddccbddddbbfff......
........c333bb333cbbfff.........
........c33cc33cc3fff...........
`;
            case "image3":
            case "box of mail":return img`
................................
..................e2222.........
..................e2222.........
.................ce2eee.........
...............ccbe2bbcc........
.............ccbbbe2bbbcc.......
...........ccbbbbbe2bbbbc.......
.........ffbbddbbbe2bbbbbc......
........ffcccbddbbccbbbbbc......
.......ffbbbddbddbcddbbbbc......
.......fbccccddbdbcddbbbbc......
.......fbcccccdbddccbbbbcc......
.......fbcccccbdbdbbbbbccf......
.......cbccccccdcdbbbccccf......
.......cbccccccbcdbccccbbf......
.......cbccccffbcbcccbbbbf......
.......cbccffffbcbcbbbbff.......
.......cbffffffbcbbbbff.........
......ccfffffffbcbbff...........
.....cbbbcfffffbcffc..6..66.....
....cbbbbbbcfffffcbc.66.6766....
...cbbbbbbbbdcff6cbc667667666...
..cbbbbbbbbddff77cbc7777777776..
.cbbbbbbbbddff777cbc77777777776.
.cdbbbbbbddff7766cbc6677777776c.
..cdbbbbddff777766666777776766c.
...cdddddff777777777777677666cc.
....ccccff777677767776766766ccb.
......677777667776676676666ccbb.
......66666bdb66bdbb6666d6ccbb..
......bddddddddddddbddddddbbb...
......bdddddddddddddddddddbb....
`;
            case "image4":
            case "suspiciously close to Godzilla":return img`
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
...........................ffffffff.................................................................
........................ffffffffffffffff............................................................
.....................ffffffffffffffffffff...........................................................
...................ffffffffffffffffffffffff.........................................................
..................fffffbbbbbbffffffffffffff.........................................................
..................fffbbffffffbffffffffffffff......f.................................................
.................ffffbfffffffffffffffffbbfff.....ff.......f.........................................
.................ffffbfffffffffffffffffffbbbf....f3f......f.........................................
................fffffffffffffffffffffffffffbf....f3f......f.........................................
....e..........fffffffffffffffffffffffffffffbf..f333f....ff.........................................
....ee........ffffffffffffffffffffffffffffffbffff333f...fff.........................................
.....e.......fffffffff9fffffffffffffffffffffbbffff333f..f33f........................................
.....ee......ffffffffffffffffffffffffffffffffbfffffff.ff333f........................................
......eeeeeeefffffffffffffffffffffffffffffffffffffffff.f3333f.......................................
..........ffefeeeeeeefffffffffffffffffffffffffffffffffff3333f.......................................
.........ffffeeffffffeeefeeffffffffffffffffffffffffffffff333f.......................................
........fffffffffffffffeefffffffffffffffffffffffffffffffff33f.......................................
.......ffffffffbfffffffffffffffffffffffffffffffffffffbffff33f.......................................
.......fffffffbbfffffffffffffffffffffffffffffffffffffbfffff3f.......................................
.......fffffbbffffffffffffffffffffffffffffffffffffffffbffffff.....ff................................
.........ffbfffffffffffffffffffffffffffffffffffffffffffffffff.....ff................................
.........fbffffffffff...fffffffffffffffffffffffffffffffffffff....f.f................................
.........bffffffff......fffffffffffffffffffffbfffffffffffffff...f3f.................................
.........ffffffff.......ffffffffffffffffffffffbbffffffffffff3f.f33f.................................
.........fffffff........ffffffffffffffffffffffffbbffffffffff3fff33f.................................
........fffffff.........ffffffffffffffffffffffffffbbffffffbffff333f.................................
.......fffffff..........ffffffffffffffffffffffffffffbbffffbffff333f.................................
......ffffff............ffffffffffffffffffffffffffffffbbffffffff33f....f............................
......ffff..............fffffffffffffffffffffffffffffffbfffffffff3f...ff............................
........................ffffffffffffffffffffffffffffffffbffffffff3f...f3f...........................
........................fffffffffffffffffffffffffffffffffbbfffffff3f.f33f...........................
.......................ffffffffffffffffffffffffffffffffffffbfbffffff.f33f...........................
.......................ffffffffffffffffffffffffffffffffffffbffbffffff333f...........................
......................ffffffffffffffffffffffffffffffffffffffbfbffffff333f...........................
....................fbfffffffbfffffffffffffffffffffffffffffffbfffffff333f...........................
...................fbbfffffffbfffffffffffffffffffffffffffffffbfffffff333f...........................
..................ffbffffffffbbffffffffffffffffffffffffffffffbffffffff33f...........................
................ffbbfffffffffffbffffffffffffffffffffffffffffffbffffffff3f...........................
...............fffbfffffffffffffbfffffffffffffffffffffffffffffbffffffff3f..f........................
..............ffffffff.....ffffffbbffffffffffffffffffffffffffffbfffffffff.ff........................
..............ffffff........fffffffbffffffffffffffffffffffffffffbfffffffffff........................
..............ffffff.........fffffffbfffffffffffffffffffffffffffbfffffffffff........................
.............ffffff...........ffffffbfffffffffffffffffffffffffffbffffffff33f........................
.............ffffff...........fffffffbffffffffffffffffffffffffffbfffffffff3f........................
..............ff...............ffffffbffffffffffffffffffffffffffbfffffffffff........................
...............................fffffffbbfffffffffffffffffffffffffbffffffffff........................
...............................fffffffffffffffffffffffffffffffffffbffffffff.f.......................
................................fffffffffffffffffffffffffffffffffffbfffffffff.......................
................................fffffffffffffffffffffffffffffffffffbffffffff........................
.................................ffffffffffffffffffffffffffffffffffbfffffffff.......................
.................................fffffffffffffffffffffffffffffffffffbffffffff.......................
.................................fffffffffffffffffffffffffffffffffffbffffffff.......................
..................................ffffffffffffffffffffffffffffffffffbfffffffff......................
..................................fffffffffffffffffffffffffffffffffffbffffffff......................
...................................ffffffffffffffffffffffffffffffffffbffffffff......................
...................................fffffffffffffffffffffffffffffffffffbffffffff.....................
...................................ffffffffffffffffffffffffffffffffffffbbffffff.....................
....................................ffffffffffffffffffffffffffffffffffffbffffff.....................
....................................ffffffffffffffffffffffffffffffffffffbfffffff....................
....................................ffffffffffffffffffbffffffffffffffffffbffffff....................
......................................fffffffffffffffbbffffffffffffffffffbffffff....................
............................................fffffffffbffffffffffffffffffffbffffff...................
...........................................fffffffffbffffffffffffffffffffffbfffff...................
........................................ffffffffffbbffffffffffffffffffffffffbfffff..................
......................................ffffffffffffbfffffffffffffffffffffffffbffffff.................
.....................................fffffffffffbbffffffffffffffffffffffffffbffffff.................
...................................fffffffffffbbffffffffffffffffffffffffffffffffffff................
..................................ffffffffffffbfffffffffffffffffffffffffffffffffffff................
..................................fffffffffffbfffffffffffffffffffffffffffffffffffffff...............
..................................fffffffffffbfffffffffffffffff.....ffffffffffffffffff..............
..................................ffffffffffbfffffffffffffffff.......fffffffffffffffff..............
..................................ffffffffffbfffffffffffffffff........fffffffffffffffff.............
...................................ffffffffbfffffffffffffffff...........fffffffffffffff.............
....................................fffffffbfffffffffffffffff............fffffffffffffff............
....................................fffffffbffffffffffffffff..............ffffffffffffff............
...................................ffffffffbffffffffffffffff...............fffffbffffffff...........
..................................fffffffffbffffffffffffffff................fffffbbfffffff..........
.................................ffffffffffbffffffffffffffff.................ffffffbfffffff.........
................................fffffffffffbfffffffffffffff....................fffffbbffffff........
...............................ffffffffffffbfffffffffffffff......................fffffbffffff.......
..............................fffffffffffffbfffffffffffffff.........................fffffffffff.....
.............................fffffffffffffffffffffffffffff............................fffffffffff...
.............................ffffffffffffffffffffffffffff................................ffffffffff.
.............................ffffffffffffff.ffffffffffff.....................................ffff.ff
.............................fffffffffffff..fffffffffff..........................................ff.
`;
            case "image1":
            case "maybe gojo":return img`
...ff1111111111ff.......
...f111111111111f.......
....ffffff11ffff........
....fdddddfff99ff..f....
...fdd99ddddd99df..fff..
...fdd99ddddddddf.fddf..
....fdddddddddddffdddf..
....fdddddddddddffd.df..
.....fddffffffddffd.df..
.....fffbccccfdff.fddf..
......fbccccccff..ffdf..
......ffccccfff...ffcf..
......fffffffcf..fbccf..
......fcccccccf..fbccf..
.....ffcccccccfffccccf..
....ffcccccccccffccccf..
..ffbbfccccccccffccff...
..fbbcffcccccfffcccf....
.ffbcccfffccffccccf.....
.fbbcccccfcfccccccf.....
.fbccccccffccccccf......
.fbcfccccccccccccf......
.fccfcccccccccccf.......
.fccfcccccccccccf.......
.fccffccccccccccf.......
.fcccfccccccccccf.......
.ffccfcccccccccff.......
..ffcffccccccccf........
...fccffccccccf.........
...fcccffffcccf.........
...ffffcccfffff.........
....fbccccfccccf........
....fbccccfccccf........
....fbccccfccccf........
....fbccccfccccf........
....ffbcccfccccf........
.....fbcccfccccf........
.....fbcccfccccf........
.....fbcccfccccf........
.....fffffffffff........
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
